name: Build & Push WebUI Docker Image

on:
  workflow_dispatch:

jobs:
  docker-webui-glibc:
    name: Build & Push WebUI Docker Image (glibc)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout A Repository
        uses: actions/checkout@v4

      - name: Checkout Tomato-Novel-Official-API (private)
        uses: actions/checkout@v4
        with:
          repository: zhongbai2333/Tomato-Novel-Official-API
          token: ${{ secrets.OAPI }}
          path: Tomato-Novel-Official-API

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta_glibc
        uses: docker/metadata-action@v5
        with:
          images: zhongbai233/tomato-novel-downloader-webui
          tags: |
            type=sha,format=short,prefix=glibc-
            type=raw,value=latest

      - name: Build and push (glibc)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.webui
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_glibc.outputs.tags }}
          labels: ${{ steps.meta_glibc.outputs.labels }}

  docker-webui-musl:
    name: Build & Push WebUI Docker Image (musl)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout A Repository
        uses: actions/checkout@v4

      - name: Checkout Tomato-Novel-Official-API (private)
        uses: actions/checkout@v4
        with:
          repository: zhongbai2333/Tomato-Novel-Official-API
          token: ${{ secrets.OAPI }}
          path: Tomato-Novel-Official-API

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta_musl
        uses: docker/metadata-action@v5
        with:
          images: zhongbai233/tomato-novel-downloader-webui
          tags: |
            type=sha,format=short,prefix=musl-
            type=raw,value=latest-musl

      - name: Build and push (musl)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.webui.musl
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_musl.outputs.tags }}
          labels: ${{ steps.meta_musl.outputs.labels }}
